# -*- coding: utf-8 -*-
import pandas as pd

df = pd.read_excel('input/通话Id.xlsx')
col = df.columns[0]
ids = df[col].tolist()
in_clause = ','.join(["'" + str(i).strip() + "'" for i in ids])

lines = []
lines.append("with calls as (")
lines.append("  select")
lines.append("    t1.action_id")
lines.append("    ,t1.call_start_time")
lines.append("    ,t1.call_time_length")
lines.append("    ,t1.user_id")
lines.append("    ,t1.worker_id")
lines.append("    ,t1.agent_name")
lines.append("    ,t1.clue_stage")
lines.append("    ,t1.regiment_id")
lines.append("    ,t1.team_id")
lines.append("  from dw.fact_call_history t1")
lines.append("  where t1.day >= 20260302 and t1.day <= 20260306")
lines.append("    and t1.action_id in (" + in_clause + ")")
lines.append(")")
lines.append("")
lines.append(", call_detail as (")
lines.append("  select")
lines.append("    c.action_id")
lines.append("    ,c.call_start_time")
lines.append("    ,substr(cast(c.call_start_time as string), 1, 19) as call_start_time_str")
lines.append("    ,c.call_time_length")
lines.append("    ,c.user_id")
lines.append("    ,c.worker_id")
lines.append("    ,c.agent_name")
lines.append("    ,c.clue_stage")
lines.append("    ,u.grade")
lines.append("    ,if(u.phone is null, u.phone, if(u.phone rlike '^\\\\d+$', u.phone, cast(unbase64(u.phone) as string))) as phone")
lines.append("    ,d2.regiment_name")
lines.append("    ,d4.team_name")
lines.append("  from calls c")
lines.append("  left join dw.dim_user u on c.user_id = u.u_user")
lines.append("  left join dw.dim_crm_organization d2 on c.regiment_id = d2.id")
lines.append("  left join dw.dim_crm_organization d4 on c.team_id = d4.id")
lines.append(")")
lines.append("")
lines.append("select")
lines.append("  cd.action_id")
lines.append("  ,cd.user_id")
lines.append("  ,cd.call_start_time_str")
lines.append("  ,cd.call_time_length")
lines.append("  ,cd.grade")
lines.append("  ,cd.clue_stage")
lines.append("  ,cd.phone")
lines.append("  ,cd.agent_name")
lines.append("  ,cd.regiment_name")
lines.append("  ,cd.team_name")
lines.append("")
lines.append("  ,nullif(concat_ws('|', collect_list(o.good_name)), '') as good_name")
lines.append("  ,sum(o.amount) as amount")
lines.append("  ,nullif(concat_ws('|', collect_list(substr(cast(o.pay_time as string), 1, 19))), '') as pay_time")
lines.append("")
lines.append("from call_detail cd")
lines.append("left join aws.crm_order_info o")
lines.append("  on cd.user_id = o.user_id")
lines.append("  and cast(cd.worker_id as int) = o.worker_id")
lines.append("  and o.good_kind_name_level_2 = '\u7ec4\u5408\u5546\u54c1'")
lines.append("  and o.status = '\u652f\u4ed8\u6210\u529f'")
lines.append("  and o.pay_time >= cd.call_start_time")
lines.append("  and to_date(o.pay_time) >= '2026-03-02'")
lines.append("  and to_date(o.pay_time) <= '2026-03-08'")
lines.append("group by")
lines.append("  cd.action_id")
lines.append("  ,cd.user_id")
lines.append("  ,cd.call_start_time_str")
lines.append("  ,cd.call_start_time")
lines.append("  ,cd.call_time_length")
lines.append("  ,cd.grade")
lines.append("  ,cd.clue_stage")
lines.append("  ,cd.phone")
lines.append("  ,cd.agent_name")
lines.append("  ,cd.regiment_name")
lines.append("  ,cd.team_name")
lines.append("limit 100000")

sql = "\n".join(lines) + "\n"

with open('code/sql/\u4e34\u65f6\u9700\u6c42/\u901a\u8bddID\u5173\u8054\u7ec4\u5408\u54c1\u6210\u4ea4\u660e\u7ec6.sql', 'w', encoding='utf-8') as f:
    f.write(sql)

print("SQL generated, {} IDs, length: {}".format(len(ids), len(sql)))
