CREATE TABLE
  `aws`.`crm_active_data_pool_day` (
    `active_u_user` string COMMENT '用户id',
    `grade` string COMMENT '年级',
    `gender` string COMMENT '性别',
    `regist_time` timestamp COMMENT '注册时间',
    `user_attribution` string COMMENT '用户注册当天归属',
    `active_user_attribution` string COMMENT '用户活跃时归属',
    `attribution` string COMMENT '用户归属',
    `channel` string COMMENT '注册渠道',
    `u_from` string COMMENT '系统平台',
    `regist_app_version` string COMMENT '注册时的app版本号',
    `regist_os` string COMMENT '操作系统',
    `regist_type` string COMMENT '注册方式',
    `city_class` string COMMENT '用户城市分线',
    `province` string COMMENT '省名称',
    `province_code` string COMMENT '省code',
    `city` string COMMENT '市名称',
    `city_code` string COMMENT '市code',
    `area` string COMMENT '区名称',
    `area_code` string COMMENT '区code',
    `real_identity` string,
    `user_pay_status_statistics` string COMMENT '统计维度：保持新增、老未、付费的标签',
    `user_pay_status_business` string COMMENT '策略维度：新用户、老用户、付费用户',
    `push_u_user` string COMMENT '当天推送到电销的用户',
    `enter_datapool_u_user` string COMMENT '当天进入到电销公海池的用户',
    `recieve_u_user` string COMMENT '当天被坐席领取的用户',
    `order_flag` string COMMENT '付费标签',
    `first_deny_reason` string COMMENT '首次进入公海池被拒绝原因',
    `first_deny_index` smallint COMMENT '首次进入公海池拒绝编号',
    `deny_index_reason_arr` string COMMENT '拒绝原因编号数组',
    `push_cnt` smallint COMMENT '当天被推送的次数',
    `datepool_cnt` smallint COMMENT '进入公海池的次数',
    `first_practice_type` string COMMENT '首次推送到电销时触发的大场景',
    `first_practice_scene` string COMMENT '首次推送到电销时触发的小场景',
    `practice_type_arr` string COMMENT '推送到电销时触发的大场景数组',
    `practice_scene_arr` string COMMENT '推送到电销时触发的小场景数组',
    `launch_order_3dcnt` int COMMENT '活跃前3天发起待支付订单个数（不含支付成功订单）',
    `pay_block_dialog_3d_cnt` int COMMENT '活跃前3天播放器付费视频阻断次数',
    `total_review_pay_block_dialog_3d_cnt` int COMMENT '活跃前3天总复习付费视频阻断次数',
    `click_study_upgrade_course_3d_cnt` int COMMENT '活跃前3天教材同步章节列表页点击升级课程按钮次数',
    `click_total_review_upgrade_course_3d_cnt` int COMMENT '活跃前3天总复习章节列表页点击升级课程按钮次数',
    `click_thinking_expanded_upgrade_course_3d_cnt` int COMMENT '活跃前3天教材同步思维拓展章节列表页点击升级课程按钮次数',
    `click_service_button_3d_cnt` int COMMENT '活跃前3天点击客服按钮次数',
    `enter_payment_page_3d_cnt` int COMMENT '活跃前3天进入订单支付详情页次数',
    `popup_payment_custservice_3d_cnt` int COMMENT '活跃前3天订单支付详情页点击人工咨询后弹出客服弹窗次数',
    `click_payment_helpdoc_3d_cnt` int COMMENT '活跃前3天订单支付详情页点击“支付帮助“次数',
    `click_payment_confirm_3d_cnt` int COMMENT '活跃前3天订单支付详情页点击"确认支付"次数',
    `click_payment_exit_stay_button_3d_cnt` int COMMENT '活跃前3天退出支付阻断弹窗内点击"我再想想"次数',
    `regist_duration` int COMMENT '注册时长(天)',
    `mid_active_type` string COMMENT '活跃类型(新增、回流、持续)',
    `all_user_clue_cnt` int COMMENT '活跃日期前，历史被销售领取次数',
    `all_add_wechat_cnt` int COMMENT '活跃日期前，历史添加过企微的次数',
    `enter_community_3d_cnt` int COMMENT '活跃前3天进入社区场景次数',
    `community_content_comment_3d_cnt` int COMMENT '活跃前3天社区内评论次数',
    `community_content_success_public_3d_cnt` int COMMENT '活跃前3天社区内成功发布内容次数',
    `enter_onion_shop_3d_cnt` int COMMENT '活跃前3天进入洋葱商店次数',
    `enter_onion_shop_exchange_dialog_3d_cnt` int COMMENT '活跃前3天洋葱商店兑换次数',
    `enter_primp_3d_cnt` int COMMENT '活跃前3天进入换装次数',
    `enter_draw_3d_cnt` int COMMENT '活跃前3天抽取服装次数',
    `user_allocation` array < string > COMMENT '用户全域服务期',
    `phone_range` string COMMENT '用户号段(手机号前3位)',
    `level` int COMMENT '活跃当天用户星阶等级',
    `click_help_center_home_menu_3d_cnt` int COMMENT '活跃前3天在帮助中心查询优惠卷次数',
    `click_nuannuan_message_button_3d_cnt` int COMMENT '活跃前3天在洋葱树洞收听音频/视频的次数',
    `click_total_reviewnew_upgrade_3d_cnt` int COMMENT '活跃前3天点击新中考总复习升级按钮次数',
    `click_exam_store_download_3d_cnt` int COMMENT '活跃前3天试卷下载阻断次数',
    `login_device_num` int COMMENT '活跃前用户历史登录设备数',
    `device_regist_uv` int COMMENT '活跃前用户当前设备注册用户数',
    `before_sum_amount` double COMMENT '截止活跃前一天用户历史累计成功付费金额',
    `user_vip_tag` string COMMENT '活跃当天用户当前会员身份标签',
    `is_bind_parent` smallint COMMENT '活跃当天是否绑定家长用户',
    `auth_type` array < string > COMMENT '用户授权类型',
    `business_user_pay_status_statistics` string COMMENT '新增(统计日期当天注册的)、大会员付费用户(统计日期之前买过大会员商品)、续费用户(统计日期之前买过正价课)、老未(统计日期之前注册的)',
    `business_user_pay_status_business` string COMMENT '大会员付费用户(统计日期之前买过大会员商品)、续费用户(统计日期之前买过正价课)、新用户(统计日期30天内注册的)、老用户(统计日期30以前注册的)',
    `risk_score` smallint COMMENT '风险分数 分数范围为【0-9】，分数越大，手机号风险值越高',
    `risk_tag` smallint COMMENT '风险标签',
    `mid_stage_name` string COMMENT '中学修正学段',
    `recieve_u_user_all` string COMMENT '当天被坐席领取的用户',
    `is_clue_seat` smallint COMMENT '线索是否在坐席名下'
  ) COMMENT '一个用户一条记录' PARTITIONED BY (`day` int) ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.orc.OrcSerde' STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat' LOCATION 'tos://yc-data-platform/user/hive/warehouse/aws.db/crm_active_data_pool_day' TBLPROPERTIES (
    'alias' = 'C端活跃用户推送公海池触发漏斗日表',
    'bucketing_version' = '2',
    'is_core' = 'true',
    'last_modified_by' = 'finebi',
    'last_modified_time' = '1749696650',
    'transient_lastDdlTime' = '1749696650'
  )